--- #YAML:1.0
name:               WWW-AtMovies-TV
version:            v0.04
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::TableExtract:  2.1
    Moose:               0.55
    Test::More:          0
    version:             0.76
    WWW::Mechanize:      1.34
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
